{% set name = "pytest-profiling" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93938f147662225d2b8bd5af89587b979652426a8a6ffd7e73ec4a23e24b7f29

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - gprof2dot
    - pytest <4.0.0
    - python
    - setuptools
    - six

test:
  imports:
    - pytest_profiling

about:
  home: https://github.com/manahl/pytest-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Profiling plugin for py.test

extra:
  recipe-maintainers:
    - pmgrafe
