travis:
  secure:
    BINSTAR_TOKEN: wTiNZXdRYNI4B8dH0rcr1Wfwoju9NvjZ6qfaeXwRK84n86IwNeWxVxjnaYD1mN6uTzWmMWBeaQnwIqE1izT+HpRgNFlS2pOOcLVGdCrh5nDaChA7SlNsPoHQEtAjjSi6MezWStm38BCligC1Dw3GzNMZujCqmlzrjAc63EgK53Dec4+xg18bEapFYVg2lpu323Mnxn3F9y8tbL21qfNVFpQXboP+vnelRz4nePx3aorUPXP9EL4hRSS0qrnZHAbX2nEY/Z6V7WTbMtSKZepnSPi+dRvg523NeQmx05/wGQVVdx0+UOTJKrSPvG01VOu+QxdeVGq0JuLvoGqRfp1urnq5qnxTh1a4G0RedByeMMNKeAOw7dByorWABLEeelVffmPCUBrk+EWxyZuSwfdXI9c3mZoV+Q91LrEHSBA4hshA8euEy6/X9lelMmCh0a+M0moQle9FDouwpFyWly8DfvximTUcwN5wosMRXeaaU4MzGF3dEiZVKeZxjjplAWu5NOCFkyZ9iYycMBJncF6QrPtvN6FTUaqa8jiVlYyvt7sbM0i8YPrJO3TV/syBo4B91H+5a+hq67rCm/UdxRPy2RpmONefoFJqpqgDw1UiwuoJ8kxrBs1NgqEpWaXc7jQqMY+TJAm1o8GkUHlK9UpjoDwX1o11ATNmf/hhi/9eaoM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
