travis:
  secure:
    BINSTAR_TOKEN: vVG+O937t19tY8YWCSRR71u1Ucew3FkQA1nQegDp6oGQwbbQ0ztUrTNoQJqSeQO44N82KkEx7z0Ny1fqfm3Y++2mpI27CExgM2sX5cZkmRI4E4Xjg0Dh0t17jDSl2IhDw2xQ1Hg7PLrdNgPvV6B5zF4w+6gKhcFACTz1FKQqo14zhjbERscDIGK2h/pVZcwusR2Dk/xD3nXTvL31uByMukER3RJ7SUSLm+a+ooMSWCBBgoOtzOmMjRu6QEHdl+OBAujy5cIt3X5mzW5FeuavOZfY0pa+q3Xb+W4lF+JsZG1Vr7cXopli6C5ciJZdN158ew+M3d6rTya4H7y/dYJDWpqp/2jUEmhYGy+5hj/JKuPYjHtX48Uxb4yPI85fXw/45nKNP+aWPN4rqij80S8nRpYvV/mjepbImy+hTU4/AY23FU492Aeqbicl1wgX2z1jS7Xp+AsOsUPHUoCpwnYf7JFrccMcCKTcCiLuZ4bacfo3VyDhvNHQUSWMT37KQ7+VySw4XOFnWLcwk0Iz85Jzjrj7SEh8N1EFfyNCAX3IlBhC5LXn0c7qXxPHmedzSCvMjTtymskR7n86ccWVZeI7IFu1RrXdknj/+6A9DsWhPBZvigV0DWXcBAz7qNbVWY5WblLGWbdfTUAtrUEMAy/GXbEzfOhOZJyxMvE+2iQvMk4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
